version: '2'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: php
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - mysql
            - memcached
        networks:
            - bitrix
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: webserver
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:8080:80'
            - '${INTERFACE}:80443:443'
        environment:
            - VIRTUAL_HOST=${LOCALHOST_ADDR}
        links:
            - php
        networks:
            - bitrix
        restart: always
    mysql:
        build: ./${MYSQL_VERSION}
        container_name: mysql
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:13306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        networks:
            - bitrix
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - bitrix
        restart: always
    source:
        image: alpine:latest
        container_name: source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/mysql:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ${SITE_PATH}:/var/www/
            - ${BITRIX_PATH}:/var/www/bitrix
            - ${SITE_PATH}/bitrix/.settings.php:/var/www/bitrix/.settings.php
            - ${SITE_PATH}/bitrix/php_interface/:/var/www/bitrix/php_interface/
        #            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrix
networks:
    bitrix:
        driver: bridge
